### ISSUE TITLE
Highlight memory usage in the README

### ISSUE THREAD

**Issue by PatWalters** [wjm41/soapgp#2]
I notice that mpi_soap.py uses ~5GB memory per MPI process.  So if you do something like mpiexec -np 12 on a machine with 64GB of memory, you'll just get a cryptic error like this.  
mpiexec noticed that process rank 0 with PID 0 on node blah exited on signal 9 (Killed).

It might be good to point this out in the README.

**Comment by wjm41** [comment]
Thanks for pointing that out! Yes I should add some pointers for typical issues that may arise in the README - will include that along with a quick code update later this week.

**Comment by wjm41** [comment]
Took a little longer than I intended because GPFlow had updated, but I've updated the code for SOAP-GP as well as the readme now :)
